# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '__first__'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('S', 'معلق'), ('P', 'در حال انجام'), ('D', 'انجام شده')], default='S', max_length=1, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='skill_images')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='service.Category')),
                ('comment_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='review.CommentSet')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user.Member')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.Skill'),
        ),
    ]
