# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='skill_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='service.Category')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user.Member')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Skill'),
        ),
    ]
