# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_member_skills'),
        ('service', '0002_auto_20160128_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tasker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user.Member'),
            preserve_default=False,
        ),
    ]
