# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20160201_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'در حال انجام'), ('D', 'انجام شده')], default='P', max_length=1, null=True),
        ),
    ]
