# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160129_1912'),
        ('service', '0004_auto_20160129_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='comment_set',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='review.CommentSet'),
            preserve_default=False,
        ),
    ]
