# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_skill_comment_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
