# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_skill_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.OrderBasket'),
        ),
    ]
