# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20160130_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.IntegerField(default=2322),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.TimeField(default=datetime.datetime(2016, 1, 30, 0, 59, 43, 208675)),
            preserve_default=False,
        ),
    ]
