# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160129_2117'),
        ('service', '0008_auto_20160130_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbasket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.Member'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderBasket',
        ),
    ]
