# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20160130_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'معلق'), ('P', 'در حال انجام'), ('D', 'انجام شده')], default='S', max_length=1, null=True),
        ),
    ]
