# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category_images'),
            preserve_default=False,
        ),
    ]
