# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25, verbose_name='عنوان')),
                ('context', models.TextField(verbose_name='متن نظر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindness', models.PositiveSmallIntegerField(default=0, verbose_name='خوش رویی')),
                ('speed', models.PositiveSmallIntegerField(default=0, verbose_name='سرعت عمل')),
                ('performance', models.PositiveSmallIntegerField(default=0, verbose_name='کارایی')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='قیمت مناسب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Tasker')),
            ],
        ),
    ]
