# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160131_2156'),
        ('service', '0004_auto_20160201_0232'),
        ('review', '0002_auto_20160131_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='نمره')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='user.Member')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='service.Order')),
            ],
            options={
                'verbose_name_plural': 'امتیازها',
                'verbose_name': 'امتیاز',
            },
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='tasker',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
