# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160129_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='customer',
        ),
    ]
