# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20160201_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='service.Order'),
        ),
    ]
