# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20160129_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.CommentSet'),
        ),
    ]
