# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20160130_2321'),
        ('review', '0007_auto_20160131_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.Member'),
            preserve_default=False,
        ),
    ]
