# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=16)),
                ('home_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=12)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank='False', choices=[('M', 'مرد'), ('F', 'زن')], max_length=1)),
                ('city', models.CharField(default='تهران', max_length=25)),
                ('district', models.CharField(default='تهران', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'کاربران نوع مشتری',
                'verbose_name': 'کاربر نوع مشتری',
            },
        ),
    ]
