# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1, null=True)),
                ('city', models.CharField(default='تهران', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر نوع مشتری',
                'verbose_name_plural': 'کاربران نوع مشتری',
            },
        ),
    ]
