# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=16)),
                ('home_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=12)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('city', models.CharField(default='تهران', max_length=25)),
                ('district', models.CharField(default='تهران', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'کاربران نوع مشتری',
                'verbose_name': 'کاربر نوع مشتری',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('morning', 'صبح'), ('noon', 'ظهر'), ('afternoon', 'بعد از ظهر'), ('full time', 'تمام وقت')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=16)),
                ('home_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=12)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('city', models.CharField(default='تهران', max_length=25)),
                ('district', models.CharField(default='تهران', max_length=25)),
                ('rate', models.IntegerField(default=0)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'خدمت گزاران',
                'verbose_name': 'خدمت گزار',
            },
        ),
    ]
