# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasker',
            name='wage',
        ),
    ]
