# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160127_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
