# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
