# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0004_auto_20160127_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(related_name='member', to='service.Skill'),
        ),
    ]
