# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_member_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
