# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='/static/images/user/profile-image-default.jpg', upload_to='profile_images'),
        ),
    ]
