# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160129_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='skills',
        ),
    ]
