# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_comment_customer'),
        ('user', '0009_remove_member_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comment_set',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='review.CommentSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
